// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Manually defining the sidebar to include files and categorize folders
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // document id (filename without the '.md' extension)
    },
    {
      type: 'doc',
      id: 'attribution', // document id
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Appendix', // assuming 'Appendix' folder exists in your docs directory
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Tutorials', // assuming 'Tutorials' folder exists in your docs directory
        },
      ],
    },
  ],
};

export default sidebars;
