// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
    },
    {
      type: 'doc',
      id: 'attributions',
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Appendix',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Tutorials',
        },
      ],
    },
  ],
};

export default sidebars;
